### ISSUE TITLE
Socket.io Server instead of an RTMP Server 

### ISSUE THREAD

**Issue by Morsmalleo** [mirsamantajbakhsh/LiveHiddenCamera#4]
Would it be possible to use this with a Socket.io Server instead of an RTMP Server??

**Comment by mirsamantajbakhsh** [comment]
Hi. As I have checked Socket.io, it seems that it does not support RTMP and has its own API. Therefore, I think you can't use this library with Socket.io.

Currently, I don't have any plan for changing the code. But any contribution is welcome.

**Comment by Morsmalleo** [comment]
> Hi. As I have checked Socket.io, it seems that it does not support RTMP and has its own API. Therefore, I think you can't use this library with Socket.io.
> 
> Currently, I don't have any plan for changing the code. But any contribution is welcome.

No you're not understanding me, I mean switch out RTMP for Socket.io, not integrate Socket.io with RTMP, sorry I should have explained that one a bit better
